### PR TITLE
Mazda TI support

### PR DESCRIPTION
**Pull request by RedFox102**
This adds the necessary changes to panda for the popular MoreTorque torque interceptor for mazda cars.

### CODE REVIEW

**Comment by rav4kumar** [comment]
@eFiniLan can you review this!

**Comment by eFiniLan** [comment]
@RedFox102 Thanks for the PR, sorry I'm not familiar with TI, with the changes in safety_mazda, does that increase the limit of controls?

would a separate safety a better option? or you think it's unnecessary? my point is not to affect non-TI user at the same time keeping the changes clean.

**Comment by RedFox102** [comment]
It works perfectly fine for TI and non-TI users, you can disconnect the TI and continue using openpilot with just the cars stock LKAS, so no reason to have a separate safety file I think.

Stock LKAS steer_max is 800 as seen here in panda safety, while TI maxes out at 600. In Mazda values.py, there are separate steer_max values for the TI (called TI_STEER_MAX), because if you send a value over 600 the TI will fault.

**Comment by eFiniLan** [comment]
@RedFox102 THANKS, could you take a look the conflict and fix that please?

@rav4kumar looks fine to me, only concern is the HEALTH_STRUCT changes,

make sure we remember to keep track of it otherwise we will have hard time debugging :joy:

**Comment by RedFox102** [comment]
@eFiniLan Yes, done.

**Comment by rav4kumar** [comment]
@RedFox102 why is HEALTH_STRUCT changed ? you need to bump it for ?

**Comment by RedFox102** [comment]
@rav4kumar We need the torqueInterceptorDetected packet to update params in controlsd. I'm glad you asked this because I forgot to update controlsd, so it wouldn't have worked. It's done now though.

**Comment by eFiniLan** [comment]
> @rav4kumar We need the torqueInterceptorDetected packet to update params in controlsd. I'm glad you asked this because I forgot to update controlsd, so it wouldn't have worked. It's done now though.

**Comment by eFiniLan** [comment]
opps.. accidentally closed it, sorry :(

**Pull request merged**
